sudo: required
language: generic
branches:
  only:
  - master
  - feature

services:
  - docker

before_install:
  - docker build -t jeffyarias/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jeffyarias/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-341956304646'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

